'''
Randomly generate a 4-digit number.                                                                                   
Ask the user to guess a 4-digit number.                                                                               
For every digit that the user guessed correctly in the correct place,they have a “cow”.                               
For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess,         
  tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over.        
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.                  

Say the number generated by the computer is 1038. An example interaction could look like this:

    Welcome to the Cows and Bulls Game!                                                                               
    Enter a number:                                                                                                   
    >>> 1234
    2 cows, 0 bulls
    >>> 1356
    1 cow, 1 bull
...
Until the user guesses the number.'''

import random as r

class Main():
  def __init__(self):
    print('Welcome to the Cows and Bulls Game! ')
    self.var = r.choice([x for x in range(1000,10000)])
    self.guess = 0
    str(self.var)
    print(self.var)

  def guess_num(self):
    while True:
      try:
        self.guessed_number = int(input('Enter a number: \n>>> '))
        break
      except:
        print('Please enter valid input.')

  def check_str(self):
    o, COW, BULL = 0, 0, 0
    self.guess += 1
    self.guess_num()
    sm = list((x , t) for t, x in zip(str(self.guessed_number), str(self.var)))
    for x in sm:
      if x[0] == x[1]:
        COW += 1
      else:
        BULL += 1
    print(f'BULL {BULL} , COW {COW}')

    if COW != 4:
      self.check_str()
    else :
      print(f'\nYou guessed it right!!\nYou guessed for {self.guess} times \n***GAME IS OVER !!!***')

main = Main()
main.check_str()